LeoSite/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    # path('', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html")),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('home/', TemplateView.as_view(template_name="home.html")),
]

article/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    # path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 上两写法等价
    path('del-article/', views.del_article, name="del_article"),
    path('edit-article/<int:id>/<slug:slug>/', views.edit_article, name="edit_article"),
    path('article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-detail/<int:id>/<slug:slug>/', list_views.list_article_detail, name="list_article_detail"),
    path('article-titles/<username>', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

article/models.py
from sre_parse import Verbose

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    """文章栏目"""
    user = models.ForeignKey(
        User, related_name="article_column", verbose_name="作者",
        on_delete=models.CASCADE)
    column = models.CharField(max_length=200, verbose_name="栏目名称")
    created = models.DateField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = "文章栏目"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(
        User, related_name="article", verbose_name="作者",
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200, verbose_name="标题")
    slug = models.SlugField(max_length=500, verbose_name="永久链接")
    column = models.ForeignKey(
        ArticleColumn, related_name="article_column", verbose_name="栏目名称",
        on_delete=models.CASCADE
    )
    body = models.TextField(verbose_name="内容")
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="article_like", blank=True)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ("-updated",)  # 排序方式为按编辑时间倒序
        index_together = (('id', 'slug'),)  # 索引字段
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)
    
    def get_absolute_url(self):  # 获取文章URL
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost


class ArticleColumnForm(forms.ModelForm):
    """文章栏目表单"""
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    """文章表单"""
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

article/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from nt import rename

from .forms import ArticleColumnForm, ArticlePostForm
from .models import ArticleColumn, ArticlePost


@login_required(login_url="/account/login")
@csrf_exempt  # 解决CSRF问题的一种方式
def article_column(request):
    """文章栏目视图"""
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(
            request,
            "article/column/article_column.html",
            {"columns": columns, "column_form": column_form})
    if request.method == "POST":
        column_name = request.POST["column"]  # 获取提交的栏目名称
        columns = ArticleColumn.objects.filter(  # 当前用户是否已有该栏目名称
            user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse("2")  # 2表示重名
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")  # 1表示允许创建


@login_required(login_url="/account/login")
@require_POST  # 只接收POST方式的提交
@csrf_exempt
def rename_article_column(request):
    """重命名文章栏目视图"""
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)  # 查询数据并重新赋值
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url="/account/login")
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除文章栏目视图"""
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login")
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()  # 用户的栏目对象，ArticleColumn.object.filter(user=request.user也可)
        return render(request, "article/column/article_post.html",
            {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url="/account/login")
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles, 10)  # 每个分页的文章数
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        current_list = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        current_list = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        current_list = current_page.object_list 
    return render(request, "article/column/article_list.html", {"articles": current_list, "page": current_page})


@login_required(login_url="/account/login")
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url="/account/login")
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login")
@csrf_exempt
def edit_article(request, id, slug):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = get_object_or_404(ArticlePost, id=id, slug=slug)  # 只用id似乎不能获取
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/edit_article.html", {
            "article": article, "article_columns": article_columns,
            "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=id, slug=slug)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id']) 
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body'] 
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

templates/article/list/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}list article detail{% endblock %}
{% block content %} 
{% with total_likes=article.users_like.count users_like=article.users_like.all %}
<div>
    <header>
        <h1>{{ article.title }}</h1> 
        <p><a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <span style="margin-left: 20px;" class="glyphicon glyphicon-thumbs-up">{{ total_likes }} 赞</span>
    </header>
    
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" /> 
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;"> 
{{ article.body }}
        </textarea>
    </div>
    <div>
        <p class="text-center">
            <a onclick="like_article({{ article.id }}, 'like')" href="#"><span class="glyphicon glyphicon-thumbs-up">赞</span></a>
            <a onclick="like_article({{ article.id }}, 'unlike')" href="#"><span class="glyphicon glyphicon-thumbs-down">踩</span></a>
        </p>
    </div>
    <p class="text-center"><strong>点赞本文的读者</strong></p>
    {% for user in article.users_like.all %}
    <p class="text-center">{{ user.username }}</p>
    {% empty %}
    <p class="text-center">还没有人点赞</p>
    {% endfor %}
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script> 
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script> 
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script> 
<script src='{% static "editor/lib/flowchart.min.js" %}'></script> 
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script> 
<script src='{% static "editor/editormd.min.js" %}'></script>
<script src='{% static "js/layer.js" %}'></script>
<script type="text/javascript"> 
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true,
    });
});
function like_article(id, action) {
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e) {
            if(e=="1") {
                layer.msg("感谢点赞！");
                window.location.reload();
            } else {
                layer.msg("我会继续努力");
                window.location.reload();
            }
        },
    });
}
</script>
{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% extends "base.html" %}
{% block title %} articles {% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
</div>
<div class="container">
    {% for article in articles %} 
    <div class="list-group">
        <a href="{{ article.get_url }}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4> 
        </a>
        <p class="list-group-item-text">作者: <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <p class="list-group-item-text">概要: {{article.body|slice:'70'| linebreaks}}</p> 
    </div>
    {% endfor %}
{% include "paginator.html" %} 
</div>
{% endblock %}

templates/article/list/author_articles.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}articles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1> 
</div>
<div class="container"> 
<div class="col-md-8">
    {% for article in articles %} 
    <div class="list-group">
        <a href="{{article.get_url}}" class="list-group-item active"> 
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者:
            <a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a>
        </p>
        <p class="list-group-item-text">概要:{{article.body|slice:'70'|linebreaks}} </p>
    </div>
    {% endfor %}
    {% include "paginator.html" %} 
</div>
<div class="col-md-4">
<div>
    {% if userinfo.photo %}
    <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face" style="width: 300px"> 
    {% else %}
    <img name="user_face" src="{% static 'images/newton.jpg' %}" class="img-circle" id="my_photo" style="width: 300px">
    {% endif %}
</div>
<div>
    <p>{{ user.username }}</p>
{% if userinfo %}
    <p>{{ userinfo.company }}</p>
    <p>{{ userinfo.aboutme }}</p>
{% else %} 
    <p>这个作者太懒了，什么也没有留下。</p> 
{% endif %}
</div>
</div>
</div>
{% endblock %}