LeoSite/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    # path('', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html")),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('home/', TemplateView.as_view(template_name="home.html")),
]

article/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    # path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 上两写法等价
    path('del-article/', views.del_article, name="del_article"),
    path('edit-article/<int:id>/<slug:slug>/', views.edit_article, name="edit_article"),
    path('article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-detail/<int:id>/<slug:slug>/', list_views.list_article_detail, name="list_article_detail"),
    path('article-titles/<username>', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

article/models.py
from sre_parse import Verbose

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    """文章栏目"""
    user = models.ForeignKey(
        User, related_name="article_column", verbose_name="作者",
        on_delete=models.CASCADE)
    column = models.CharField(max_length=200, verbose_name="栏目名称")
    created = models.DateField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = "文章栏目"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(
        User, related_name="article", verbose_name="作者",
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200, verbose_name="标题")
    slug = models.SlugField(max_length=500, verbose_name="永久链接")
    column = models.ForeignKey(
        ArticleColumn, related_name="article_column", verbose_name="栏目名称",
        on_delete=models.CASCADE
    )
    body = models.TextField(verbose_name="内容")
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="article_like", blank=True)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ("-updated",)  # 排序方式为按编辑时间倒序
        index_together = (('id', 'slug'),)  # 索引字段
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)
    
    def get_absolute_url(self):  # 获取文章URL
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost


class ArticleColumnForm(forms.ModelForm):
    """文章栏目表单"""
    class Meta:
        model = ArticleColumn
        fields = ("column",)


class ArticlePostForm(forms.ModelForm):
    """文章表单"""
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

article/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from nt import rename

from .forms import ArticleColumnForm, ArticlePostForm
from .models import ArticleColumn, ArticlePost


@login_required(login_url="/account/login")
@csrf_exempt  # 解决CSRF问题的一种方式
def article_column(request):
    """文章栏目视图"""
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(
            request,
            "article/column/article_column.html",
            {"columns": columns, "column_form": column_form})
    if request.method == "POST":
        column_name = request.POST["column"]  # 获取提交的栏目名称
        columns = ArticleColumn.objects.filter(  # 当前用户是否已有该栏目名称
            user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse("2")  # 2表示重名
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")  # 1表示允许创建


@login_required(login_url="/account/login")
@require_POST  # 只接收POST方式的提交
@csrf_exempt
def rename_article_column(request):
    """重命名文章栏目视图"""
    column_name = request.POST["column_name"]
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)  # 查询数据并重新赋值
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url="/account/login")
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除文章栏目视图"""
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login")
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()  # 用户的栏目对象，ArticleColumn.object.filter(user=request.user也可)
        return render(request, "article/column/article_post.html",
            {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url="/account/login")
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles, 10)  # 每个分页的文章数
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        current_list = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        current_list = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        current_list = current_page.object_list 
    return render(request, "article/column/article_list.html", {"articles": current_list, "page": current_page})


@login_required(login_url="/account/login")
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url="/account/login")
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login")
@csrf_exempt
def edit_article(request, id, slug):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = get_object_or_404(ArticlePost, id=id, slug=slug)  # 只用id似乎不能获取
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/edit_article.html", {
            "article": article, "article_columns": article_columns,
            "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=id, slug=slug)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id']) 
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body'] 
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %} {% block content %}
<div>
    <p class="text-right"><!--button class="btn btn-primary">add column</button-->
        <button id= "add_column" onclick="add_column()" class="btn btn-primary">添加栏目</button>
    </p> 
    <table class="table table-hover">
        <tr> 
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td> 
        </tr>
        {% for column in columns %} 
        <tr>
            <td>{{ forloop.counter }}</td> 
            <td>{{ column.column }}</td> 
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"> 
                    <span class="glyphicon glyphicon-pencil"></span>    
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span> 
                </a>    
            </td>
        </tr>
        {% empty %} 
        <p>还没有设置栏目，太懒了。</p> 
        {% endfor %}
    </table> 
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "js/layer.js" %}'></script>
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增栏目",
            content: '<div class="text-center" style="margin-top:20px">\
                <p>请输入新的栏目名称</p><p><input type="text" id="id_column"></p></div>',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: {"column": column_name},
                    success: function(e) {
                        if (e=="1") {
                            parent.location.reload();
                            layer.msg("添加成功");
                        } else {
                            layer.msg("此栏目已存在，请更换名称")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }
    function edit_column(the, column_id) {
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "编辑栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>请编辑栏目名称</p><p><input type="text" id="new_name" value="' + name + '"></p></div>',
            btn: ['确定', '取消'],
            yes: function(index, layero) {
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name},
                    success: function(e) {
                        if (e=="1") {
                            parent.location.reload();
                            layer.msg("修改成功！");
                        } else {
                            layer.msg("修改失败！");
                        }
                    },
                });
            },
        });
    }
    function del_column(the, column_id) {
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除' + name + '栏目？</p></div>',
            btn: ['确定', '取消'],
            yes: function() {
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type: "POST",
                    data: {"column_id": column_id},
                    success: function(e) {
                        if (e=="1") {
                            parent.location.reload();
                            layer.msg("删除成功！");
                        } else {
                            layer.msg("删除失败！");
                        }
                    },
                });
            },
        });
    }
</script>
{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %} 
<div>
    <header>
        <h1>{{ article.title }}</h1> 
        <p>{{ user.username }}</p>
    </header>
    
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" /> 
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;"> 
{{ article.body }}
        </textarea>
    </div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script> 
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script> 
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script> 
<script src='{% static "editor/lib/flowchart.min.js" %}'></script> 
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script> 
<script src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript"> 
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true,
    });
});
</script>
{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %} 
<div>
    <table class="table table-hover"> 
        <tr>
            <td>序号</td>
            <td>标题</td> 
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td> 
            <td>{{ article.column }}</td>
            <td>
                <a name="edit" href="{% url 'article:edit_article' article.id article.slug %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_article(this, {{ article.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left: 20px;"></span>
                </a>
            </td>
        </tr>
        {% endfor %} 
    </table>
    {% include "paginator.html" %}
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script> 
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script> 
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text(); 
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],    
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p></div>',
            btn: ['确定', '取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type:"POST",
                    data: {"article_id": article_id},
                    success: function(e){
                        if(e=="1"){ 
                            parent.location.reload(); 
                            layer.msg("删除成功");
                        }else{ 
                            layer.msg("删除失败");
                        }
                    },
                })
            }, 
        });
    } 
</script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}"> 
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %} 
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div> 
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div> 
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{column.id}}">{{column.column}}</option> 
                    {% endfor %}
                </select> 
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <div class="col-md-10 text-left" id="editormd"><textarea style="display: none;" id="id_body"></textarea></div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script> 
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script> 
<script type="text/javascript">
function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val(); 
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:article_post' %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id}, 
        success: function(e){
            if(e=="1"){ 
                layer.msg("添加成功");
                location.href = "{% url 'article:article_list' %}";
            }else if(e=="2"){ 
                layer.msg("添加失败") ;
            }else{ 
                layer.msg("请输入项目名称。");
            } 
        },
    }); 
}
</script>

<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script> 
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            syncScrolling : "single",
            path : "{% static 'editor/lib/' %}"
        }); 
    });
</script>

{% endblock %}

templates/article/column/edit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}edit article{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div>
    <header>
        <h1>{{ article.title }}</h1> 
        <p>{{ user.username }}</p>
    </header>

    <div class="container">
        <div class="col-md-10">
        <div style="margin-left:10px">
            <form class="form-horizontal" action="." method="post">{% csrf_token %} 
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>标题:</span></div>
                    <div class="col-md-10 text-left">{{this_article_form.title}}</div> 
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>栏目:</span></div> 
                    <div class="col-md-10 text-left">
                        <select id="which_column">
                            {% for column in article_columns %}
                                {% if column == this_article_column.column %}
                                    <option value="{{column.id}}" selected="selected">{{column.column}} </option>
                                {% else %}
                                    <option value="{{column.id}}">{{column.column}}</option>
                
                                {% endif %} 
                            {% endfor %}
                        </select> 
                    </div>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>内容:</span></div> 
                    <div id="editormd" class="col-md-10 text-left">
                        <textarea style="display:none;" id="id_body"> 
        {{article.body}}
                        </textarea> 
                    </div>
                </div>
                <div class="row">
                    <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
                </div>
            </form>
        </div>
        </div>
    </div>

</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/editormd.min.js" %}'></script>
<script src='{% static "js/layer.js" %}'></script>
<script type="text/javascript"> 
$(function(){
    var editor = editormd("editormd", { 
        width : "100%",
        height : 640,
        path : "{% static 'editor/lib/' %}", 
    });
});
function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val(); 
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:edit_article' article.id article.slug %}", 
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id}, 
        success: function(e){
            if(e=="1"){ 
                layer.msg("修改成功");
                location.href = "{% url 'article:article_list' %}"; 
            }else{
                layer.msg("修改失败"); 
            }
        }, 
    });
}
</script>
{% endblock %}