LeoSite/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('admin/', admin.site.urls),
    # path('', include('blog.urls')),
    path('', TemplateView.as_view(template_name="home.html")),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('home/', TemplateView.as_view(template_name="home.html")),
]

account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views  # 使用内置方法登录和退出

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('new-login/', auth_views.login, {'template_name': 'account/login.html'}),
    path('logout/', auth_views.logout, {'template_name': 'account/logout.html'}, name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.password_change, {'post_change_redirect': '/account/password-change-done'}, name='password_change'),
    path('password-change-done/', auth_views.password_change_done, name='password_change_done'),
    path('password-reset/', auth_views.password_reset, {"template_name":"account/password_reset_form.html", "email_template_name":"account/password_reset_email.html", "subject_template_name":"account/password_reset_subject.txt",  "post_reset_redirect":"/account/password-reset-done"}, name="password_reset"),
    path('password-reset-done/', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"}, name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.password_reset_confirm, {"template_name":"account/password_reset_confirm.html", "post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.password_reset_complete, {"template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
]

article/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    # path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name="article_detail"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),  # 上两写法等价
    path('del-article/', views.del_article, name="del_article"),
    path('edit-article/<int:id>/<slug:slug>/', views.edit_article, name="edit_article"),
    path('article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-detail/<int:id>/<slug:slug>/', list_views.list_article_detail, name="list_article_detail"),
    path('article-titles/<username>', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="http://apps.bdimg.com/libs/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
{% include "header.html" %}
<div class="container">
{% block content %}
{% endblock %}
</div>
{% include "footer.html" %}
<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

templates/content.html
{% extends "base.html" %}

{% block title %}博客文章内容{% endblock %}

{% block content  %}
<div class="row text-center vertical-middle-sm">
<h1>{{ article.title }}</h1>
</div>
<div class="row">
<div class="col-xs-12 col-md-8">
<p class="text-center">
<span>{{ article.author.username }}</span>
<span style="margin-left:20px">{{ publish }}</span>
</p>
<div>{{ article.body }}</div>
</div>
<div class="col-xs-6 col-md-4">
<h2>广告</h2>
<p>我的作品</p>
</div>
{% endblock %}

templates/footer.html
<div class="cointainer">
<hr>
<p class="text-center">@2018: LeoSite</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
<nav class="navbar navbar-default" role="navigation">
<div class="navbar-header">
<a class="navbar-brand" href="/">我的站点</a>
</div>
<div>
<ul class="nav navbar-nav" role="navigation">
<li><a href="/">首页</a></li>
<li><a href="{% url 'blog:blog_title' %}">博客</a></li>
<li><a href="{% url 'article:article_titles' %}">文章</a></li>
</ul>
<ul class="nav navbar-nav navbar-right" style="margin-right:10px">
{% if user.is_authenticated %}
<li>
<div class="dropdown" style="margin-top:8px">
<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
{{ user.username }}<span class="caret"></span>
</button>
<ul class="dropdown-menu">
<li><a href="{% url 'account:password_change' %}">修改密码</a></li>
<li><a href="{% url 'account:my_information' %}">个人信息</a></li>
<li><a href="{% url 'article:article_column' %}">后台管理</a></li>
</ul>
</div>
</li>
<li><a href="{% url 'account:user_logout' %}">退出</a></li>
{% else %}
<li><a href="{% url 'account:user_login' %}">登录</a></li>
<li><a href="{% url 'account:user_register' %}">注册</a></li>
{% endif %}
</ul>
</div>
</nav>
</div>

templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
<div class="text-center">
    <h1>WELCOM YOU</h1>
    <h3>Life is short. You need Python</h3>
    <h2>Django makes it easier to build better Web apps more quickly and with less
code.</h2>
    {% load staticfiles %}
    <img src="{% static 'editor/images/logos/editormd-logo-320x320.png' %}">
</div>
{% endblock %}

templates/paginator.html
<div class="pagination"> 
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">上一页</a> 
        {% endif %}
        <span class="current">
            第 {{ page.number }} 页，共 {{ page.paginator.num_pages }} 页
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">下一页</a> {% endif %}
    </span>
</div>

templates/titles.html
{% extends "base.html" %}

{% block title %}博客文章列表{% endblock %}

{% block content  %}
<div class="row text-center vertical-middle-sm">
<h1>我的博客</h1>
</div>
<div class="row">
<div class="col-xs-12 col-md-8">
<ul>
{% for blog in blogs %}
<li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
{% endfor %}
</ul>
</div>
<div class="col-xs-6 col-md-4">
<h2>广告</h2>
<p>我的作品</p>
</div>
{% endblock %}